version: "3.4"

services:
  identityserver:
    image: identityserver
    container_name: identityserver
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
    ports:
      - '5000:5000'
    networks:
      - my-network

  resource.api:
    image: resource.api
    container_name: resource.api
    build:
      context: .
      dockerfile: Resource.Api/Dockerfile
    ports:
      - '5050:5050'
    networks:
      - my-network
      
  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: oauth-client/Dockerfile
    ports:
      - '4200:80'
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge